### ISSUE TITLE
Recommended to add screenshots to the docs

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfchain_tft#10]
https://github.com/threefoldtech/tfchain_tft/blob/main/tfchain_bridge/transfers.md
docs is not clear enough specially second part: [TF Chain to Stellar]

recommend to add screenshot for each step
Ex:
![Screenshot from 2021-10-06 12-21-30](https://user-images.githubusercontent.com/16083592/136185653-55957c91-c7eb-461c-8a1f-a5c1cd88dbea.png)

**Comment by DylanVerstraete** [comment]
Yes, only instead of target being Freddy (or any other of the known accounts) it should be your account or and account of someone you know. The target is the target stellar address but in SS58 format (tfchain)

**Comment by DylanVerstraete** [comment]
added in: https://github.com/threefoldtech/tfchain_tft/commit/37131b662162ff74f510e34927773c1cfc43a6a0
