### ISSUE TITLE
bridge address as a destination account not exist 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/tfchain_tft#11]
can't transfer to bridge address: GCMBZY4NGEV4CQYHJ6SXMRSTLTEOR2ERNKY6NH32LYCVDCN2E5CXZJOU
 
![image](https://user-images.githubusercontent.com/31102305/136185634-7b30af57-a33d-4292-96df-56e9a738ddbe.png)

```jumpscale.core.exceptions.exceptions.Runtime: Failed to make transaction for 5 times, Please try again later
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hassan/jumscales/js-sdk/jumpscale/clients/stellar/stellar.py", line 492, in transfer
    raise j.exceptions.Runtime(f"Failed to make transaction for {retries} times, Please try again later")
          │                                                      └ 5
          └ <jumpscale.loader.J object at 0x7fab0f76deb0>
jumpscale.core.exceptions.exceptions.Runtime: Failed to make transaction for 5 times, Please try again later

Failed to make transaction for 5 times, Please try again later
```

**Comment by xmonader** [comment]
you should create the client with 'TEST' flag

```
JS-NG> c = j.clients.stellar.new("todelete2", network='TEST')                                                                     
JS-NG> c                                                                                                                          
Stellar(
  instance_name='todelete2',
  network=<Network.TEST: 'TEST'>,
  address='GBV2SIPWHJUUSO4HCPK466PET2AYDPHG7D4VJARCTQMHXPIN5BBKZEYM',
  sequence=0,
  sequencedate=0,
  secret='SDVSNXOX2BXPC3FKYBJLKMEJF4UMAVEN5DX6DKCPQYF7T2X6PM3G23GW'
)


```

**Comment by DylanVerstraete** [comment]
> you should create the client with 'TEST' flag
> 
> ```
> JS-NG> c = j.clients.stellar.new("todelete2", network='TEST')                                                                     
> JS-NG> c                                                                                                                          
> Stellar(
>   instance_name='todelete2',
>   network=<Network.TEST: 'TEST'>,
>   address='GBV2SIPWHJUUSO4HCPK466PET2AYDPHG7D4VJARCTQMHXPIN5BBKZEYM',
>   sequence=0,
>   sequencedate=0,
>   secret='SDVSNXOX2BXPC3FKYBJLKMEJF4UMAVEN5DX6DKCPQYF7T2X6PM3G23GW'
> )
> ```

And insert the secret generated with the `keygen` tool:

```
JS-NG> c = j.clients.stellar.new("todelete2", network='TEST', secret="STELLAR_SECRET")                                                                     

```
